config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.resources :contatos

  map.resources :eventos

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'

end

app/models/contato.rb
# == Schema Information
#
# Table name: contatos
#
#  id         :integer         not null, primary key
#  nome       :string(255)     not null
#  email      :string(255)     not null
#  telefone   :string(255)
#  celular    :string(255)
#  endereco   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Contato < ActiveRecord::Base

  validates_presence_of :nome, :email
  validates_uniqueness_of :email

  has_and_belongs_to_many :eventos, :uniq => true

end

app/models/evento.rb
# == Schema Information
#
# Table name: eventos
#
#  id         :integer         not null, primary key
#  descricao  :text            not null
#  data_hora  :datetime        not null
#  local      :string(255)     not null
#  titulo     :string(255)     not null
#  created_at :datetime
#  updated_at :datetime
#

class Evento < ActiveRecord::Base

  validates_presence_of :descricao, :data_hora, :local, :titulo
  has_and_belongs_to_many :contatos, :uniq => true

end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
  protected

  def carrega_pagina
    @pagina = params[:pagina] || '1'
    @por_pagina = (params[:por_pagina] || '30').to_i
    @por_pagina = 30 if @por_pagina > 30
    true
  end

end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController

  gerar_para Contato

end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  gerar_para Evento
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper

  def will_paginate(collection = nil, options = {})
    options[:previous_label] = 'Anterior'
    options[:next_label] = 'Próximo'
    super(collection, options)
  end

end

app/helpers/eventos_helper.rb
module EventosHelper

  def contatos_para_select( selecionados )
    options_for_select(
      Contato.all.map { |c| [c.nome, c.id ] },
      selecionados )
  end

end

app/views/contatos/_form.html.erb
<% form_for @contato, :builder => AgendaFormBuilder do |f| %>

    <%= f.error_messages %>

    <%= f.text_field :nome %>
    <%= f.text_field :email %>
    <%= f.text_field :celular %>
    <%= f.text_field :telefone %>
    <%= f.text_field :endereco %>

    <%= f.submit %>

<% end %>

app/views/contatos/edit.html.erb
<h2>Alterar Contato</h2>

<%= render :partial => 'form' %>

app/views/contatos/index.html.erb
<h2>Contatos</h2>

<p> <%= link_to 'Novo Contato', new_contato_path %>
<% unless @contatos.blank? %>

  <%= will_paginate @contatos %>

  <p>Encontrado(s) <%= @contatos.size %> registro(s).</p>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>Celular</th>
      </tr>
    </thead>
    <tbody>
      <% for contato in @contatos %>
        <tr id="<%= dom_id contato %>">
          <td><%= contato.nome %></td>
          <td><%= contato.email %></td>
          <td><%= contato.telefone %></td>
          <td><%= contato.celular %></td>
          <td><%= link_to 'Alterar', edit_contato_path(contato)%></td>
          <td><%= link_to 'Excluir', contato, :confirm => 'Você tem certeza?',
                                              :method => :delete %>
          </td>
          <td><%= link_to_remote 'Excluir com ajax',
                                  :url => contato_url( contato ),
                                  :method => :delete,
                                  :confirm => 'Você tem certeza?' %>
          </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem contatos cadastrados</p>
<% end %>

app/views/contatos/new.html.erb
<h2>Novo Contato</h2>

<%= render :partial => 'form' %>

app/views/eventos/_form.html.erb
<% form_for @evento, :builder => AgendaFormBuilder do |f| %>
  <%= f.text_field :titulo %>
  <%= f.text_area  :descricao %>
  <%= f.text_field :local %>
  <%= f.datetime_select :data_hora %>
  <%= f.select :contato_ids, Contato.all.map { |c| [c.nome, c.id] }, :include_blank => true %>
  <p>Contatos:</p>
  <%= select_tag 'evento[contato_ids]',
                          contatos_para_select( @evento.contato_ids ),
                          :multiple => true %>
  <p>Checkboxes:</br>
    <% for contato in Contato.all %>
      <%= check_box_tag 'evento[contato_ids]',
            contato.id,
            @evento.contato_ids.include?(contato.id) %>
      <%= contato.nome %>
      <br />
    <% end %>
  </p>
  <%= f.submit %>
<% end %>

app/views/eventos/edit.html.erb
<h2>Alterar Evento</h2>

<%= render :partial => 'form' %>

app/views/eventos/index.html.erb
<h2>Eventos</h2>

<p> <%= link_to 'Novo Evento', new_evento_path %>
<% unless @eventos.blank? %>

  <%= will_paginate @eventos %>

  <p>Encontrado(s) <%= @eventos.size %> registro(s).</p>
  <table>
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Local</th>
        <th>Data</th>
      </tr>
    </thead>
    <tbody>
      <% for evento in @eventos %>
        <tr id="<%= dom_id evento %>">
          <td><%= evento.titulo %></td>
          <td><%= evento.local %></td>
          <td><%= evento.data_hora %></td>
          <td><%= link_to 'Alterar', edit_evento_path(evento)%></td>
          <td><%= link_to 'Excluir', evento, :confirm => 'Você tem certeza?',
                                              :method => :delete %>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem eventos cadastrados</p>
<% end %>

app/views/eventos/new.html.erb
<h2>Novo Evento</h2>

<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Agenda</title>
    <%= javascript_include_tag :all, :cache => 'todos' %>
  </head>
  <body>
    <%  [ :notice, :error ].each do |m| %>
      <% unless flash[m].blank? %>
        <div class="<%= m %>">
          <%= flash[m] %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>